[[project]]
name  = "Void (working title)"
desc  = "A quick moving, flick shooting, fps game, based around platforming and puzzle solving. Requires quick thinking and precise shooting. Currently in development using Godot 4."
links = []
